"""add color cols

Revision ID: 29fba17e5543
Revises: 98bdec1c0d52
Create Date: 2022-11-08 10:04:53.179317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29fba17e5543'
down_revision = '98bdec1c0d52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("unis", sa.Column("color", sa.String(), nullable=False))
    op.add_column('unis', sa.Column('text_color', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unis', 'text_color')
    op.drop_column('unis', 'color')
    # ### end Alembic commands ###
